os: linux
sudo: required
language:
  - minimal
services:
  - docker

jobs:
  include:
    - name: "compile"
      script:
        - chmod 755 scripts/*.sh
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/compile.sh


notifications:
  email: false

